services:
  bot:
    image: ibertran/42squad
    build: .
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - API42_UID=${API42_UID}
      - API42_SECRET=${API42_SECRET}
      - LOG_CHANNEL_ID=${LOG_CHANNEL_ID}
      - SECRET_OWNER_ID=${SECRET_OWNER_ID}
      - INTERVAL_SECONDS=${INTERVAL_SECONDS}
    restart: unless-stopped
    volumes:
      - database:/app/db

volumes:
  database: